#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$app = sprout()->createApp([
    'name' => 'Seedling',
    'autoload' => __DIR__ . '/app/console',
    'version' => sprout()->composer()->version() ?? '0.1.0',
]);

$app->register([
    \Leaf\Sprout\Seedling::commands(),
    \Leaf\Sprout\Seedling::moduleCommands()
]);

exit((int) ($app->run(false) ?? 0));
